### ISSUE TITLE
Support static initialization of a `Logger`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/logging#7]
Currently we provide a convenient way for adding a `Logger` to a class via `WithLogging` interface. It mixes in the `logger` property, which returns the result of `LoggingFactory.loggerFor(this::class)`.

Sometimes, especially in the Java code, we need to have a `static private` instance of `Logger`. Currently, we do it like this:

```java
public class TempArtifactDirs {

    private static final Logger<?> log = LoggingFactory.getLogger(
            getKotlinClass(TempArtifactDirs.class)
    );

    ...
}
```

It's too much of a ceremony! Users need to know about the `LoggingFactory`. Then they need to take care of the conversion of a Java class to its Kotlin counterpart. It is not convenient. 

What we need to have is an analogue of the call `FluentLogger.forEnclosingClass()`  provided by Flogger.

**Comment by yevhenii-nadtochii** [comment]
Addressed in #36.
